# Generated by Django 6.0.3 on 2026-04-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0002_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20),
        ),
    ]
