# Generated by Django 6.0.3 on 2026-03-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0003_remove_pago_cliente_pago_usuario_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20),
        ),
    ]
