# Generated by Django 6.0.3 on 2026-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0004_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
