# Generated by Django 6.0.3 on 2026-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0006_alter_inscripcion_options_pago_cantidad_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='clases_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
