# Generated by Django 6.0.3 on 2026-03-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0007_alter_perfil_clases_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
