# Generated by Django 6.0.3 on 2026-04-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0008_perfil_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
    ]
