# Generated by Django 6.0.3 on 2026-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_gym', '0010_alter_perfil_options_movimientocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='categoria',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(max_length=200),
        ),
    ]
