"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv # Importamos la librería

load_dotenv() # Cargamos el archivo .env

BASE_DIR = Path(__file__).resolve().parent.parent

# Ahora leemos la clave desde el archivo secreto
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'  

# Esto permite que funcione en tu PC y en la URL que te de Render
ALLOWED_HOSTS = ['*'] # Para la primera prueba, luego lo limitamos


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_gym',
    'kiosco',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <-- Asegúrate de que diga esto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

JAZZMIN_SETTINGS = {
    # Título de la ventana del navegador
    "site_title": "Gym Violet Admin",
    # Título en la pantalla de logueo
    "site_header": "Gym Violet",
    # Logo de la marca (puedes poner un png en static y rutearlo aquí)
    "site_brand": "Panel de Control",
    # Mensaje de bienvenida
    "welcome_sign": "Bienvenido al Sistema de Gestión del Gimnasio",
    # Copyright en el footer
    "copyright": "Gym Violet Ltd",
    
    # Iconos para las secciones del menú lateral
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "gestion_gym.Clase": "fas fa-dumbbell",
        "gestion_gym.Pago": "fas fa-money-bill-wave",
        "gestion_gym.Inscripcion": "fas fa-clipboard-list",
    },
    
    # Nombres más bonitos para las secciones
    "order_with_respect_to": ["gestion_gym.Clase", "gestion_gym.Pago", "gestion_gym.Inscripcion", "auth"],
    
    # Colores de los botones y links (Violeta para seguir tu estética)
    "accent": "primary",
    "default_theme_mode": 'dark', 
    "show_ui_builder": False,

    "topmenu_links": [
    {"name": "Ir al Kiosco", "url": "kiosco", "permissions": ["auth.view_user"]},
    {"name": "Reporte Ganancias", "url": "reporte_ganancias"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark", # Esto lo hace oscuro
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary", # Aquí es donde se pone el tono oscuro pro
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly", # Este es el tema oscuro por defecto
    "dark_mode_theme": "darkly",
    "changeform_format": "horizontal_tabs",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'